package com.plexus.personal.document.infrastructure;
import com.plexus.personal.document.domain.*;
import org.apache.ibatis.annotations.*;
import java.util.*;
@Mapper public interface DocumentMapper {
 @Select("select id,user_id,original_filename,storage_key,media_type,file_extension,file_size,sha256,status,failure_reason,raw_text,normalized_text,quality_status,quality_score,review_result,created_at,updated_at from documents where user_id=#{userId} order by created_at desc") @Results(id="documentResult", value={@Result(property="id",column="id"),@Result(property="userId",column="user_id"),@Result(property="originalFilename",column="original_filename"),@Result(property="storageKey",column="storage_key"),@Result(property="mediaType",column="media_type"),@Result(property="fileExtension",column="file_extension"),@Result(property="fileSize",column="file_size"),@Result(property="sha256",column="sha256"),@Result(property="status",column="status"),@Result(property="failureReason",column="failure_reason"),@Result(property="rawText",column="raw_text"),@Result(property="normalizedText",column="normalized_text"),@Result(property="qualityStatus",column="quality_status"),@Result(property="qualityScore",column="quality_score"),@Result(property="reviewResult",column="review_result"),@Result(property="createdAt",column="created_at"),@Result(property="updatedAt",column="updated_at")}) List<DocumentRow> findByUserId(Long userId);
 @Select("select id,user_id,original_filename,storage_key,media_type,file_extension,file_size,sha256,status,failure_reason,raw_text,normalized_text,quality_status,quality_score,review_result,created_at,updated_at from documents where id=#{id} and user_id=#{userId}") @ResultMap("documentResult") DocumentRow findById(@Param("id") Long id,@Param("userId") Long userId);
 @Insert("insert into documents(user_id,original_filename,storage_key,media_type,file_extension,file_size,sha256,status) values(#{userId},#{originalFilename},#{storageKey},#{mediaType},#{fileExtension},#{fileSize},#{sha256},#{status})") @SelectKey(statement="select currval('documents_id_seq')", keyProperty="id", before=false, resultType=Long.class) int insert(DocumentRow row);
 @Delete("delete from documents where id=#{id} and user_id=#{userId}") int delete(@Param("id") Long id,@Param("userId") Long userId);
 @Update("update documents set status=#{status},failure_reason=#{reason},updated_at=current_timestamp where id=#{id} and user_id=#{userId}") int updateStatus(@Param("id") Long id,@Param("userId") Long userId,@Param("status") String status,@Param("reason") String reason);
 @Update("update documents set raw_text=#{rawText},normalized_text=#{normalizedText},quality_status=#{qualityStatus},quality_score=#{qualityScore},review_result=#{reviewResult},status=#{status},failure_reason=#{reason},updated_at=current_timestamp where id=#{id} and user_id=#{userId}") int updateQuality(@Param("id") Long id,@Param("userId") Long userId,@Param("rawText") String rawText,@Param("normalizedText") String normalizedText,@Param("qualityStatus") String qualityStatus,@Param("qualityScore") Double qualityScore,@Param("reviewResult") String reviewResult,@Param("status") String status,@Param("reason") String reason);
}
